version: "3.9"

services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hardpassword
      POSTGRES_DB: test
    volumes:
      - ./docker_volume/db-data/:/var/lib/postgresql/data/
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:2743"
    ports:
      - "3000:3000" # Maps port 8080 on the host to port 80 in the container
    depends_on:
      - backend # Ensure the backend service is started first
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2743:2743"
    environment:
      PORT: 2743
      DATABASE_URL: "postgresql://postgres:hardpassword@db:5432/mydatabase" # Example DB connection
    depends_on:
      - db # Ensure the database service is started first
    networks:
      - app_network

networks:
  app_network:
