version: "3.9"

services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hardpassword
      POSTGRES_DB: test
    volumes:
      - ./docker_volume/db-data/:/var/lib/postgresql/data/
    networks:
      - app_network

networks:
  app_network:
