apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-management
data:
  NODE_ENV: production
  PORT: "1378"
  DATABASE_URL: postgresql://postgres:hardpassword@database:5432/taskdb
