apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: task-management
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 1378
      targetPort: 1378
