apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: task-management
spec:
  type: LoadBalancer # Use NodePort for Minikube external access
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
